add lecture04
kinta21/RaiseTech-AWS pull request #4
Opened 2024-04-09 03:26 UTC by kinta21

## 概要
###  第4回課題を提出
- AWS 上に VPC を作成
- EC2 の構築
- RDS の構築
- EC2 へ SSH 接続
- EC2 から RDS へ接続

2024-04-09 12:01 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！

2024-04-09 12:01 UTC, MasatoshiMizumoto commented on lecture04/lecture04.md
最後の画像が重複な気がしますが、ご確認ください！

2024-04-09 23:58 UTC, kinta21 commented on lecture04/lecture04.md
lecture04の修正を行いました。ご確認宜しくお願いします。
- `` ## EC2 へ SSH 接続
![EC2へSSH接続](lecture04-img/ssh-ec2.png) `` を削除
- lecture04-imgからssh-ec2.pngの削除

2024-04-10 04:40 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！

2024-04-10 04:40 UTC, MasatoshiMizumoto commented on lecture04/lecture04.md
うーん、意図した修正ではないのでもう一度どのような形であるべきか考え直していただきたいです！
課題はどのような姿があるべき形なのでしょう？
作っただけでは課題達成ではないので、となると何を示せば良いのでしょう？

2024-04-10 09:22 UTC, kinta21 commented on lecture04/lecture04.md
lecture04の修正を行いました。ご確認宜しくお願いします。
https://github.com/kinta21/RaiseTech-AWS/pull/4/commits/5f20e268a0ff906e10d094335ec36cc965dada90

- lecture04/lecture04-img/ssh-ec2.pngの修正

2024-04-10 10:24 UTC, MasatoshiMizumoto approved these changes
LGTMです！！

2024-04-10 23:24 UTC, merged